### ISSUE TITLE
Als je een github account hebt

### ISSUE THREAD

**Issue by RooieDirk** [htool/vhfinfo#4]
Mijn fork verwijderd, maar gaat nog steeds niet goed. Vermoedelijk omdat ik een github account heb.
Bij 'commit' klikken, krijg ik dit. (Vandaar ook dat ik een fork gemaakt had)
![Screenshot_20230107_103635](https://user-images.githubusercontent.com/2668258/211144127-fa857e4c-4e4b-44b6-a336-1df84b3ae05b.png)

**Comment by htool** [comment]
Dat lijkt te kloppen als ik bijv dit lees:
https://design-system.service.gov.uk/community/propose-a-content-change-using-github/

Kun je kijken hoe het gaat als je daar de fork maakt?

**Comment by htool** [comment]
Net incognito gedaan:
 - commit
 - greate new github account
 - after signup, close github window
 - commit again
 - create fork
 - delete/paste
 - 'Propose changes'

**Comment by htool** [comment]
Daarna wordt het als het goed is:
 - create form
 - delete/paste
 -  Propose changes

**Comment by htool** [comment]
Ah, ik zie dat er in de fork daarna nog een 'Compare & create pull request' moet worden gedaan.
Ik zal dat duidelijker maken in de popup.

**Comment by htool** [comment]
Moet nu weg, dus wordt vanavond pas.

**Comment by htool** [comment]
Github accounts zijn nu geen probleem meer.
